### ISSUE TITLE
ArgumentError (wrong number of arguments (given 1, expected 0))

### ISSUE THREAD

**Issue by GuskiS** [wmakley/simple_serializer#3]
When I do:
```ruby
render json: { data: UserSerializer.new(current_user) }
```
I get `ArgumentError (wrong number of arguments (given 1, expected 0))`
there isn't much of stacktrace, but it points to https://github.com/wmakley/simple_serializer/blob/master/lib/simple_serializer.rb#L99

However, if I do:
```ruby
render json: { data: UserSerializer.new(current_user).as_json }
```
it works just fine.

I tried adding:
```ruby
  def as_json(data)
    binding.pry
  end
```
to serializer, `data` seems to be `{}` 🤔

**Comment by wmakley** [comment]
This is my recommended usage now:

    render json: { data: UserSerializer.new(current_user).serialize }

I just added some parameters to fix your use case though. I just forgot that ActiveSupport expected #as_json and #to_json to take an options parameter.

**Comment by GuskiS** [comment]
Btw, just tried adding:
```ruby
  def as_json(data = {})
    super()
  end
```
and it seems to be working.

**Comment by wmakley** [comment]
Yeah the issue was my as_json implementation didn't take any arguments.
