### ISSUE TITLE
Use blank instead of empty

### ISSUE THREAD

**Issue by GuskiS** [wmakley/simple_serializer#4]
https://github.com/wmakley/simple_serializer/blob/master/lib/simple_serializer.rb#L81

Use `.blank?` instead of `.empty?` cause `.empty?` creates database query `ModelName Exists`.

See for more: https://gist.github.com/AmitPatel-BoTreeConsulting/bd47d07a303956ba8b56

I think having `.blank?` will be fine cause you are going to work with that array anyway.

**Comment by wmakley** [comment]
Thanks, I hadn't thought about collections too hard yet. Solved a bug I had noticed in my logs actually.

I'd like the collection handling to be more explicit, it out of line with my peeves with AMS to handle them automatically, but it saved me time when I was deleting AMS.

**Comment by GuskiS** [comment]
IIRC, `blank?` was purely array/enum method, while `empty?` is ActiveRecord(or ActiveSupport) magic, so using `blank?` on ActiveRecord collection firstly transforms it to array and then checks length.

Anyways, I really enjoy this gem. I have the same reason as you for not using AMS. I even created issue https://github.com/rails-api/active_model_serializers/issues/2053 but didn't get any useful info.

Thank you for creating this 👍

**Comment by wmakley** [comment]
Thanks! I realized I shouldn't even be calling any other methods on the collection, since my definition of a collection is something that responds to `each` and not `each_pair`.
