### ISSUE TITLE
Options API

### ISSUE THREAD

**Issue by trevorrjohn** [wmakley/simple_serializer#5]
I started to try to transition from AMS 0.8, however I am running into issues where I want to pass in options to the serializer. If you are not familiar, options is just metadata that you can use when you are serializing the object.

I was thinking something like:

```ruby
class ItemSerializer < SimpleSerializer
  attribute :foo do |object, options|
    object.foo if options[:include_foo]
  end
end

> item = Struct.new(:foo).new('foo')
> ItemSerializer.new(item, options: { include_foo: true }).serialize
{ foo: 'foo' }
> ItemSerializer.new(item, options: { include_foo: false }).serialize
{ foo: nil }
```

Thoughts? I am open to working on this if this is something you would consider.

**Comment by wmakley** [comment]
I never used that feature, but you are welcome to submit a PR if you have time to work on it! I probably won't for a week or two. Just add an options parameter to the constructor, and pass it to `instance_exec`.
